### ISSUE TITLE
Pb de rendu sur les estuaires

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-bzh/osmbr-mapstyle#27]
Il y a au moins 1 an une modification des données a fait que les estuaires était asséchés.

Les 2 zones sur lesquelles je m’en suis rendu compte :
- estuaire de la vilaine : https://kartenn.openstreetmap.bzh/#map=14/47.4945/-2.4125
- ria d’Etel

**Comment by MaelREBOUX** [comment]
Réglé par la simple mise à jour des données petites échelles avec https://github.com/osm-bzh/osmbr-mapstyle/commit/668629c9935d9c8a46f48b05a4f9fc9e5d8e4d46

avant
![Capture d’écran 2020-05-10 à 12 33 54](https://user-images.githubusercontent.com/6370443/81496809-ad763900-92ba-11ea-9d83-7b58de8093f8.png)

après
![Capture d’écran 2020-05-10 à 12 34 20](https://user-images.githubusercontent.com/6370443/81496814-b36c1a00-92ba-11ea-9de3-af34665e2dbd.png)

Merci à Jean-Yvon et Marc marc pour la relance.

**Comment by MaelREBOUX** [comment]
J'ai purgé les tuiles sur le rendu br de 20 -> 13.
Je laisse qqs jours pour voir si les réglages d'expiration automatiques prennent le relais (7 j max).

https://kartenn.openstreetmap.bzh/#map=12/47.7021/-3.1624

**Comment by pyrog** [comment]
Ça commence à se mettre à jour dans l'[estuaire de la Gironde :<br/>
<img width="373" alt="Capture d’écran 2020-05-10 à 15 23 30" src="https://user-images.githubusercontent.com/2158081/81500408-541a0400-92d2-11ea-8132-25f67f644e56.png">](http://tile.openstreetmap.fr/?zoom=8&lat=45.239&lon=-0.49741&layers=0000000B0FFFF)

PS: original le nom de Bordeaux en Occitan 😄

**Comment by MaelREBOUX** [comment]
Et la Ria d'étel retrouve son eau à toutes les échelles. Les réglages d'expiration ont fait leur œuvre.
Cool.

![Capture d’écran 2020-05-19 à 22 16 47](https://user-images.githubusercontent.com/6370443/82373840-77555980-9a1e-11ea-851e-97730e504733.png)
